name: "PHP CodeSniffer"

on: [push, pull_request]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.json
        run: composer validate
        
      - name: Install composer²
        run: composer install
      
      - name: Install PHP_CodeSniffer composer package
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Validate PSR-12 Code style
        run: ~/.composer/vendor/bin/phpcs