name: "PHP CodeSniffer"

on: [push, pull_request]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.json
        run: composer validate
        
      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Validate PSR-12 Code style
        run: ./vendor/bin/phpcs -p